version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: innovacionMovil2024*
      MYSQL_DATABASE: bd1
  php:
    build: .
    image: php:8.1-apache
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: innovacionMovil2024*
volumes:
  db_data: